//Write a Java method that returns the sum of all even Fibonacci numbers. Consider all Fibonacci numbers that are less than or equal to n. Each new element in the Fibonacci sequence is generated by adding the previous two elements.
//
//        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//        Constraints:
//        The following constraint applies for the input integer number n: 1<n≤1000
//
//        Even though the classic Fibonacci sequence starts with the first two integers: 1 and 1, in the given problem, the Fibonacci sequence starts with 1 and 2.
package Quiz;

import java.util.ArrayList;
import java.util.Scanner;

public class SumEvenFibonacciNumbers {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int number = scanner.nextInt();
        ArrayList<Integer> numbers = new ArrayList<Integer>();

        numbers.add(0);
        numbers.add(1);
        int size = 1;
        while(numbers.get(size)<number){
            numbers.add(numbers.get(size-1)+numbers.get(size));
            size++;
        }

        int total= 0;
        for (int i = 0; i <= size; i++) {
            if (numbers.get(i)%2==0 && numbers.get(i)<=number){
                total+=numbers.get(i);

            }
        }

        System.out.println(total);

    }
}

