# Generated by Django 3.1.6 on 2021-02-16 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 2, 16, 14, 36, 40, 767850))),
            ],
        ),
    ]
