# Generated by Django 3.1.6 on 2021-02-20 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Действие', 'verbose_name_plural': 'Действия'},
        ),
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('N', 'Not Completed'), ('I', 'In Progress')], default='N', max_length=15),
        ),
        migrations.AlterField(
            model_name='action',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 16, 52, 4, 62466)),
        ),
    ]
